local char = workspace.X_masLucas7 

local weld1 = Instance.new("WeldConstraint")
weld1.Parent = char
weld1.Part0 = char.LeftLowerArm
weld1.Part1 = char.LeftUpperArm 
local weld2 = Instance.new("WeldConstraint")
weld1.Parent = char
weld1.Part0 = char.RightLowerArm
weld1.Part1 = char.RightUpperArm 
local weld3 = Instance.new("WeldConstraint")
weld1.Parent = char
weld1.Part0 = char.LeftLowerLeg
weld1.Part1 = char.LeftUpperLeg
local weld4 = Instance.new("WeldConstraint")
weld1.Parent = char
weld1.Part0 = char.RightLowerLeg
weld1.Part1 = char.RightUpperLeg

local weld5 = Instance.new("WeldConstraint")
weld5.Parent = char
weld5.Part0 = char.LeftUpperArm
weld5.Part1 = char.LeftLowerArm 
local weld6 = Instance.new("WeldConstraint")
weld6.Parent = char
weld6.Part0 = char.RightUpperArm
weld6.Part1 = char.RightLowerArm 
local weld7 = Instance.new("WeldConstraint")
weld7.Parent = char
weld7.Part0 = char.LeftUpperLeg
weld7.Part1 = char.LeftLowerLeg
local weld8 = Instance.new("WeldConstraint")
weld8.Parent = char
weld8.Part0 = char.RightUpperLeg
weld8.Part1 = char.RightLowerLeg
